webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/curation/MergeCas.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/curation/component/model/SuggestionBuilder.java

New Curation Cas Merge + TestCase

 #1878 - chili - Refactoring and adding Test cases for suggestion

---

.gitignore
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

AnnotationDetailEditorPanel.class: minor changes here and there

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ProjectServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/SettingsServiceImpl.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctorUtils.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsAndDeleteExtrasRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingChainLinksRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java
webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/diag/repairs/RemoveDanglingRelationsRepairTest.java
webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsIndexedCheckTest.java
webanno-dkprocore/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/segmentation/type/SurfaceForm_Type.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java
webanno-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialog.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageBase.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemServiceImpl.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelRegistryServiceImpl.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/MergeCas.java

- Replace lambda with method reference
- Replace anonymous type with lambda
- Replace Collection.sort() with List.sort()
- Replace statement lambda with expression lambda
- Simplify comperator by using the static method Comperator.comparingInt()

#486 - Refactoring project structure (3.3.0) 

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/AutomationCasStorageServiceImpl.java
webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfReader.java
webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/WebAnnoSemanticGraphReader.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebannoTsv1Reader.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebannoTsv2Reader.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebannoTsv3Reader.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebannoTsv3Writer.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectUsersPanel.java

- Make use of StringBuilder.append() instead concatenation
- Inline variable and remove cast

#486 - Refactoring project structure (3.3.0)

---

webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java

#520 - Perform javascript action on click

---

CONTRIBUTORS.txt

Since I contributed a little bit to webanno my name may could be in the CONTRIBUTORS.txt file.

Add 'Aleks Stier' to CONTRIBUTORS.txt

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/AnnotationPreferenceModalPanel.java

Fixed a bug which was causing inconsistent behavior when selecting / deselecting layers in preference view.
- quick fix enable/disable layers in preference view

#531 - adaptive coloring strategy

---

webanno-doc/src/main/asciidoc/user-guide/installation.adoc

Docker image for WebAnno #497

---

webanno-webapp/pom.xml
webanno-webapp/src/main/docker/Dockerfile
webanno-webapp/src/main/docker/docker-compose.yml

- repaired Dockerfile
- make sure docker container runs in en_US.UTF-8 locale
- minor adjustments in docker-compose 
- corrected volume directory
- reduced memory usage for docker container

#622 - Repair dockerfile in accordance to standalone jar

---

pom.xml
webanno-model-export/pom.xml

Please merge it, otherwise mvn build failed

Fix web model dependeny version problem, update to 3.4.0

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VArc.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VObject.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VSpan.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeUtil.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/Entity.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/display/model/EntityTest.java
webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/AnnotationFeature.java
webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/AnnotationLayer.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/layers/ProjectLayersPanel.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/layers/ProjectLayersPanel.java

Customize text shown in the hoverboxes for span annotations similar to the labeltext.

#587 Customize mouse hover text - patch

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.html

New PR from the proper branch.
It doesn't wrap nicely, but its less messy than before.

#669 - Fix overflowing text in ProjectImportPanel

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java

added support for non-visible (regarding brat span label) features in hover text

Customize mouse hover text #587

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/AnnotationPreferencesDialogContent.java

Fixes to the annotation user preferences dialog to fix #663.

#663 - It is possible to add annotation on disabled layers

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js

- Create selectable stretching spacer element between chunks
- Adjust annotation creation code to handle spacer elements

#316 - Text selection behavior while dragging mouse

---

pom.xml
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentStateType.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/PersistentEnumUserType.java
webanno-webapp/src/main/resources/META-INF/database-context.xml

#716 - Upgrade to Spring 5

---

webanno-api-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/model/AutomationStatus.java
webanno-api-automation/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/automation/model/db-changelog.xml
webanno-doc/src/main/asciidoc/admin-guide/settings.adoc
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TrainingDocument.java
webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
webanno-security/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/security/model/db-changelog.xml
webanno-webapp/pom.xml
webanno-webapp/src/main/resources/application.properties
webanno-webapp/src/main/resources/db/changelog/db.changelog-master.xml

Introduce Liquibase as a database migration manager.

#748 - Introduce database migration manager

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java

- BeforeDocumentRemovedEvent is now the first action febore the removal

#765 - Trigger BeforeDocumentRemovedEvent before removing annotation documents

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java

fix NullPointerException by initializing list of preferred layers to all layers

#755 - Error opening settings dialog in curation mode

---

webanno-ui-core/NOTICE.txt
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/kendo/WicketJQueryFocusPatch.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/kendo/WicketJQueryFocusPatchBehavior.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/kendo/wicket-jquery-focus-patch.js

Monkey patching special handling for Kendo ComboBox and Kendo NumericTextBox into the Wicket Focus code.

#772 - ComboBox feature editor not focussed on annotation selection

---

webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java

#795 a space character needed for a valid SQL

---

webanno-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController2.java

#798 Remove a slash at the end from document deletion API

---

webanno-api-dao/pom.xml
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ProjectInitializer.java
webanno-io-tcf/pom.xml
webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfReader.java
webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfWriter.java

Adding the TCF Orthography layer, with two features called correction and operation as webanno TCF reader and writer component

#825 Add orthography layer into TCF reader

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

* Clear selection of feature list when clicking "Create" or "Cancel" in the feature details panel.

#846 -  Layer Settings: Feature selected but details not shown

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

- Trigger LayerConfigurationChangedEvent whenever the save button is
submitted, both for layer and feature changes

Trigger LayerConfigurationChangedEvent after any changes to layers or features

---

webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/AutomationServiceEventAdapter.java

set TRAIN and OTHER features to null before deleting the Mira Template

#879 Unable to delete automation project

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarRegistryImpl.java

- Use order for sorting if existing, else use display name

#881 Use stable order in left side bar

---

webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectSelectionPanel.java

- listAccessibleProjects now lists all projects in which the user is
admin / annotator / curator
- New method listManageableProjects to select only the projects in which
the user is a manager

#890 - listAccessibleProjects should include projects in which the user is an annotator or curator

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistry.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistryImpl.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/FeatureEditor.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraitsEditor.html
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraitsEditor.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaBehavior.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaChoiceRenderer.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaModelAdapter.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/SerializableFunction.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

#898 - Allow feature-type specific configurations

---

pom.xml

- Update Maven plugi
- Update checkstyle dependency
- Added workaround to make the setup with with the code-quality Eclipse plugin

#909 - Update checkstyle (again)

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

- Save layer settings always when save button is pressed, not only when a new layer is created.

#924 - Renaming layer is not working

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraits.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.html
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java

- Added a default slots trait in the link feature details
- Generate default slots in the link feature editor based on the trait

#918 - Link feature trait for default slots

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java

- Move recalculateProjectState from DocumentServiceImpl to ProjectService
- Do not require special permissions for recalculateProjectState

#940 - Updating project state requires higher privileges

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java

- Hide project type choice if there is only one type

#942 - Hide project type choice if only one type is available

---

webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java

- Run only a single query with a limit of 1. If there is a user, return it, if not, return null.

#947 - Avoid second query when fetching user

---

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java

- Do not try to fetch an annotation document in correction/automation modes

#955 - Correction/automation mode broken

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/model/TsvSubToken.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java

- Added checks ni DocumentServiceImpl and some in UserDaoImpl

#949 - Check mandatory arguments

---

pom.xml

- Spring Boot 1..5.10 -> 1.5.13
- Spring Security 4.2.4 -> 4.2.6
- Wicket Bootstrap 0.10.16 -> 0.10.17
- Wicket Spring Boot 1.0.10 -> 1.0.12

#974 - Upgrade dependencies (3.5.0)

---

webanno-api-dao/pom.xml
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/JsonImportUtil.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/ajax/controller/CasToBratJsonTest.java
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/display/model/EntityTest.java
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/display/model/RelationTest.java
webanno-model-export/pom.xml
webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedProject.java
webanno-support/pom.xml
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
webanno-ui-project/pom.xml
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

- Create a new mapper when one is needed.

#979 - Decouple JSONUtil from the spring context

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java

- Removed one of the duplicate methods

#977 - Duplicate method in DocumentService

---

webanno-project/pom.xml
webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/SourceDocumentStateStats.java
webanno-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/SourceDocumentStateStatsTest.java

- Fixed calculation of project state
- Moved SourceDocumentStateStats into a separate class
- Created unit test to check if all states are defined

#990 - Error at loading document into Curation

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java

- Hide the form group of forwarding is not possible

#838 - If "Forward annotation" is not allowed on a layer, hide the option

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java

- Adding back the assignment to importedProject which was accidentally removed during refactoring

#997 - After importing a project, the projects settings doesn't update

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorFactory.java
webanno-api-dao/pom.xml
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/BackupProperties.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/RepositoryProperties.java
webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java
webanno-api-dao/src/test/resources/log4j2.xml
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/JCasProvider.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditorFactory.java
webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController2Test.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarFactory.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebar_ImplBase.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/docinfo/DocumentInfoSidebar.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/docinfo/DocumentInfoSidebarFactory.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java

- Refactoring access to annotations and initial CAS ensuring that accesses are synchronized in critical points

#1005 - Race condition when accessing annotations can lead to data loss

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.java

- Add user list and detail panel to the AJAX refresh

#1000 - "Cancel" button in user management has no effect

---

pom.xml
webanno-api-automation/pom.xml
webanno-api-dao/pom.xml
webanno-api/pom.xml
webanno-automation/pom.xml
webanno-constraints/pom.xml
webanno-curation/pom.xml
webanno-model-export/pom.xml
webanno-model/pom.xml
webanno-project/pom.xml
webanno-remote/pom.xml
webanno-security/pom.xml
webanno-support/pom.xml
webanno-ui-annotation/pom.xml
webanno-ui-automation/pom.xml
webanno-ui-project/pom.xml

- Spring Boot -> 1.5.14
- Spring Security -> 4.2.7
- HSQLDB -> 2.4.1
- Hibernate -> 5.3.2.Final

#974 - Upgrade dependencies

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistry.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistryImpl.java

- Added a custom authorization strategy that takes into account the menu item visibility

#892 - Do not load the project page if the user does not have the proper rights

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.java

- Disable the "open" button when no document is selected

#1017 - Improve "open document" dialog

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java

- Fetch the latest state of the document when determining if it is finished as the document info in the annotator state may be stale

#816 - Refreshing the curation page doesn't result in correct state after changing state in API

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java

- Add new readAnnotationCas function which uses the user name

#1024 - Create AnnotationDocument for user when using readAnnotationCas

---

webanno-webapp/pom.xml

- Upgraded MySQL driver to version 8.0.11

#1026 - Upgrade to recent MySQL driver

---

webanno-constraints/src/main/resources/META-INF/asciidoc/user-guide/constraints.adoc

- Fixed mis-leading and non-working "line comments" in example rules
- Documented how the block comments work

#1036 - Document how comments in constraint rules files work

---

webanno-io-conll/pom.xml
webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllCoreNlpReader.java
webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllCoreNlpWriter.java
webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/sequencecodec/AdjacentLabelCodec.java
webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/sequencecodec/SequenceCodec.java
webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/sequencecodec/SequenceItem.java
webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllCoreNlpReaderWriterTest.java
webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/sequencecodec/AdjacentLabelCodecTest.java
webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/sequencecodec/SequenceItemTest.java
webanno-io-conll/src/test/resources/conll/corenlp/en-orig.conll
webanno-io-conll/src/test/resources/conll/corenlp/en-ref.conll
webanno-webapp/src/main/resources/META-INF/formats.properties

- Back-ported ConllCoreNlpReader/Writer

#1047 - Add support for the CoreNLP CoNLL flavor

---

webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml

- Added constraint in Project entity class
- Added corresponding liquibase changeset

#1053 - Add non-null statement to project.mode column

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.properties

- Added variable in properties file

#1055 - Use product name variable in warning about using embedded DB

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java

- Ensure that the project mode is set not only when the panel is constructed but also every time the model changes

#1057 - Project mode may become null if only one project type is available

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnchoringMode.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects.adoc

- Added the "sentence-level" option for granularity
- Moved getMultipleAnnotation out of the SpanAdpater and into the AutomationUtil
- Removed unused methods from SpanAdpater

#393 - Sentence-level annotation

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraitsEditor.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java

- Ensure to notify detail panel of model change when the feature selection is changed via the list
- Set objects though setter methods of key components that use them
- Bit of refactoring from inner classes to using setters and lambdas

#1069 - Feature traits editor does not always show up

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/ProjectSettingsExporter.java

- Set the mode before initially persisting the project during import
- Renamed variables and changed messages to reflect that we are in the "import" stage

#1071 - Unable to import projects

---

webanno-api/pom.xml
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/SecurityUtil.java
webanno-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageMenuItem.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPageMenuItem.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.html
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItem.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPageMenuItem.java
webanno-ui-core/src/main/resources/META-INF/asciidoc/user-guide/menu.adoc
webanno-ui-core/src/main/resources/META-INF/asciidoc/user-guide/menubar.adoc
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPageMenuItem.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPageMenuItem.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPageMenuItem.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPageMenuItem.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPageMenuItem.java

- Add "getPath()" to the menu item interface
- Make username in the menu bar a link to the users profile (if the user can see/edits the own profile)
- Added menubar documentation

#1065 - Refactor menu items

---

webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml

- Refactored changeset to work on HSQLDB

#443 - "Lock to token offsets" and "Allow multiple tokens" are hard to understand

---

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPage.java
webanno-ui-project/pom.xml
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.java

- Refactored project settings page

#1074 - Permit pages to be called with pre-set project

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.html
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.properties
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.java

- Reorganized users page
- Introduced validator for the user name
- User name only editable when user is being created
- User more I18N on the page
- Fixed bug that duplicate user names would not be reported
- Fixed bug that feedback messages are not being displayed
- Better use of Wicket 8 lambda support

#1086 - NPE when trying to update user

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java

- Introduce methods for opportunistic CAS upgrade
- Use them in the agreement page

#1090 - Fast opportunistic CAS upgrade

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/SourceDocumentExporter.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExportRequest.java
webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/export/AutomationTrainingDocumentExporter.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctorException.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllFeatureStructuresIndexedCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/FeatureAttachedSpanAnnotationsTrulyAttachedCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/LinksReachableThroughChainsCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoZeroSizeTokensAndSentencesCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/RelationOffsetsCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsAndDeleteExtrasRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReindexFeatureAttachedSpanAnnotationsRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RelationOffsetsRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingChainLinksRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveZeroSizeTokensAndSentencesRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/Repair.java
webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/diag/repairs/RemoveDanglingRelationsRepairTest.java
webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsIndexedCheckTest.java
webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheckTest.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/LogLevel.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/LogMessage.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java

- Improve logging during project export
- Move CasDoctor LogMessage into the support module so that it can be used elsewhere (e.g. during project export)

#1094 - Improve error logging during project export

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratProperties.java
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java

- Configuration setting for the "remember layer" default

#1098 - Allow configuration of default value for "remember layer" and similar settings

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java

- Introduce an interface for PreRenderer and use that for injection into Wicket components

#1108 - Annotation, Curation, Automation pages fail on master branch

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java

- Pass "NEW" as project id to create a new project
- Move "cancel" and "delete" buttons from the detail tab to the top-level so they are visible irrespective of which tab is selected

#1116 - Allow creating a new project via page parameter

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-vis.css
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebar_ImplBase.java

- Configure marker looks via CSS classes

#1119 - Improve control over markers

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/PermissionsExporter.java

- Always import the permissions of the importing user even if import of full permissions was not requested

#1114 - Import projects for non-admins

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java

- Initialize CASes with all relevant types (including internal ones) on document import

#368 - Make possible to delete features and whole layers

---

webanno-model/pom.xml
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevel.java

- Use the old values for project export/import for compatibility reasons

#1126 - Rename project roles

---

webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff2.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java

- Read layer configuration only once per document, not once per sentence.

#1135 - Curation slowed down due to excessive DB access

---

webanno-api-annotation/pom.xml
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/config/PrimitiveUimaFeatureSupportProperties.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
webanno-brat/pom.xml
webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/ajax/controller/CasToBratJsonTest.java
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc

- Increased default limit for auto-complete field to 100
- Made activation threshold and limit for auto-complete field configurable via settings.properties

#1138 - Combobox limit 25

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java

- Added listAllDocuments method.
- Moved around a few methods in the code so similar methods are closer together.

#1146 - Make it possible to list all <SourceDocument, AnnotationDocument> pairs

---

webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java

Add method to read JSON from InputStream

#1148 - Add method to read JSON from InputStream

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ArcAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/AutomationTypeAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java

- Deprecated methods that accept the AnnotatorState
- Introduce methods which user document/username

#1150 - Avoid passing AnnotatorState to TypeAdapter

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExportService.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java

- Handle the export state in the runnable

#1174 - Export may fail without good reason

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/ProjectConstraintsPanel.java

- Do not delete file after download is complete

#1164 - Exporting a constraints file deletes it

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExportRequest.java
webanno-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/ExportUtil.java
webanno-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java

- Use format ID instead of format name when exporting via remote API

#954 - Allow optionally specifying a format on project export

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationCrossSentenceBehavior.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanCrossSentenceBehavior.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageBase.java

- Optimized performance of SpanCrossSentenceBehavior.onValidate() and RelationCrossSentenceBehavior.onValidate()
- Added trace-level log messages allowing to see how long validation takes
* Import a huge document (can be only text since the Token layer is validated as well)
* Open it in the annotation editor and try marking it as finished

#1205 - Finishing takes forever in annotation/curation for certain documents

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java

- Fixed export of only curated documents by setting the project on the export request
- Bit of reorganization of the code into a more readable/modern structure
* Have a project with files marked as finished on the curation page
* Export only curated documents from that project via the export panel in the project settings

#1215 - Error when trying to export only curated documents

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/css/theme/custom.less

- Increase z-index for feedback messages

#1230 - Bootstrap dropdowns rendered above feedback messages

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/PermissionsExporter.java

- Properly generate all missing permissions

#1235 - Manager does not receive all project roles on import

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java

- Special rendering of boolean features prefixing the UI label with + or -
* Create a layer with a boolean feature
* Create an annotation on that layer

#1228 - aliases for boolean features

---

webanno-ui-core/pom.xml
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java

- Made the dependency on webanno-remote optional
* Check if code still compiles / runs

#1244 - webanno-ui-core should not hard-depend on webanno-remote

---

pom.xml
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/Select2TextFeatureEditor.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java

- Spring 5.1.3.RELEASE -> 5.1.5.RELEASE
- Spring Boot 1.5.18.RELEASE -> 1.5.19.RELEASE
- Wicket 8.1.0 -> 8.3.0
- Wicketstuff 8.1.0 -> 8.3.0
- Wicket Bootstrap 2.0.6 ->2.0.7
- Wicket JQuery Selectors 2.0.2 -> 2.0.4
- Wicket Webjars 2.0.8 -> 2.0.11
* Use application

#1247 - Upgrade dependencies (3.6.0)

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorViewState.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff2.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java

- Remove uses of Sentence JCas wrapper class causing ClassCastExceptions because we no longer initialize JCas
* Just use the application and basically try out anything imaginable. The change was pervasive.

#1261 - Switch from JCas to CAS

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Fail creation of relation if there is no relation layer defined on the spans between which the relation is being created
- Fail creation of relation between spans on different layers
Backend only - cannot be tested manualls.

#1272 - Check whether relation can be created between spans is bad

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/PartOfSpeechLayerInitializer.java

- Adjust UI names and descriptions for POS layer and features
- Add coarse-grained POS feature

#1270 - Importing CONLL-U losing UPOS tags

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanOverlapBehavior.java
webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapterTest.java

* Fix wrong overlap check
* See issue descrption

#1284 - Adjacent annotations sometimes wrongly considered to be overlapping

---

webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentService.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPage.java

- Add progress indicator for CURATION user
* Check if the curation user shows up in the charts on the monitoring page

#1275 - Show progress information for curation

---

webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfWriter.java
webanno-io-tcf/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfReaderWriterTest.java

- Port fix from DKPro Core
* Export project with TCF format

#1303 - Unable to export in TCF format

---

pom.xml

- Spring -> 5.1.7.RELEASE
- Spring Boot -> 1.5.21.RELEASE
- Spring Security -> 4.2.12.RELEASE
* Build, run, see if things still work

#1247 - Upgrade dependencies

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java

- Add upgradeCas to interface and make it public
* Build it and see whether it gives no errors

#1309 - Make CAS upgrade public

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java

- Add the position label to the AJAX target when paging

#1313 - Position information not updated

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasMetadataUtils.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllFeatureStructuresIndexedCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/FeatureAttachedSpanAnnotationsTrulyAttachedCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsAndDeleteExtrasRepair.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsRepair.java
webanno-ui-automation/pom.xml
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/project/ProjectMiraTemplatePanel.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java

- Add missing breaks in switch/case statements when the granularity was checked
- Fixed wrongly detecting a concurrent change to the CAS file when using automation
- Less verbose checks/repairs

#1307 -  Automation of Annotation

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/ProjectSettingsExporter.java
webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedProject.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
webanno-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.properties

- Added option for blind curation to the project settings
* Enable anonymous curation in the project settings detail panel
* Visit the curation page with a user who does have the curator role but not the manager role in the project

#1320 - Blind curation

---

webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.properties
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.html
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.java

- Add a toggle to the users list on the user management page
* Go to the user management page
* Disable a user
* Switch between displaying enabled/disabled users using the checkbox at the bottom

#1324 - Toggle between enabled/disabled users

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/LegacyProjectInitializer.java
webanno-api-dao/src/main/resources/tagsets/de-ne-webanno.json

- Fixed description
* Check out the description in a freshly created project

#1316 - Wrong description for default tag

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java

- Removed the check for built-in layers
- Formatting and fixing typo
* Try creating a relation layer e.g. on Named Entities
* Annotate with these releations

#1331 - Allow custom relations on built-in layers

---

webanno-codebook/pom.xml
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/annotation/CodebookEditorPanel.java

Implementation very similar to the one in ClassicKendoComboboxTextFeatureEditor.
Actually it's almost a copy & paste.
* it's fixing the issue #1334
* start WebAnno, open a Codebook Project and mouse-over the annotations and codebooks
* no tests available
* not yet

 #1334 Adding Tooltips for Codebook annotations

---

webanno-api-annotation/src/main/resources/META-INF/asciidoc/developer-guide/annotation-schema-layer-behavior-extensions.adoc

* some tips around developing LayerBehaviors

Extend documentation on developing custom behaviors

---

webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java

- Kill existing session when logging in so we always log in to a new session
* Nothing to test.

#1351 - Invalidate session when logging in

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java

- Make sure the CAS gets the right timestamp on reset
* Try resetting a document on the annotation page

#1359 - Concurrent modification error when resetting document

---

webanno-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/XmiFormatSupport.java

- Set flag to import XMI leniently
* Import any XMI file with types not declared in the project.

#1366 - XMI files again not read leniently

---

webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasSchemaAnalyzer.java
webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/model/TsvSchema.java

- Set up list of "ignored" types during schema analysis
- Skip processing annotations from these types when building the TSV3 internal data model
* Nothing to rest really - TSV3 test suite still runs through

#1386 - Improve TSV export times by skipping non-exported layers

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java

- Changed resource reference to JQuery v3
* Use application, check if it works, in particular JS-based stuff like the brat UI

#1397 - Switch to JQuery v3

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/AnnotationEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/BulkAnnotationEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/ChainEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/ChainLinkCreatedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/ChainLinkDeletedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/ChainSpanCreatedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/ChainSpanDeletedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/FeatureValueUpdatedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/RelationCreatedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/RelationDeletedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/RelationEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/SpanCreatedEvent.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/SpanEvent.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/AfterCasWrittenEvent.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java

- Introduce event hierarchy
- Added events for chain actions
- Added event for bulk actions
* Nothing particular to test

#1399 - Improve annotation internal annotation events

---

pom.xml
webanno-plugin-api/LICENSE.txt
webanno-plugin-api/pom.xml
webanno-plugin-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/api/ExportedComponent.java
webanno-plugin-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/api/ExportedComponentPostProcessor.java
webanno-plugin-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/api/Plugin.java
webanno-plugin-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/api/PluginManager.java
webanno-plugin-manager/LICENSE.txt
webanno-plugin-manager/pom.xml
webanno-plugin-manager/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/impl/PluginManagerImpl.java
webanno-plugin-parent/LICENSE.txt
webanno-plugin-parent/pom.xml
webanno-webapp/pom.xml
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java

- Added plugin manager and plugin API modules
- Added plugin loading mechanism to WebAnno boot class
- Added plugin parent module
* Build a plugin ;)

#1368 - PF4J-based plugin system

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.java

Removed adding new label from boolean feature editor.

#1406 BooleanFeature Editor does not render

---

webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/export/CodebookExporter.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/model/CodebookCategory.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/model/CodebookFeature.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/model/CodebookTag.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/service/CodebookSchemaService.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/service/CodebookSchemaServiceImpl.java
webanno-api-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/service/PrimitiveUimaCodebookFeatureSupport.java
webanno-api-codebook/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/codebook/model/db-changelog.xml
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ImportUtil.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/annotation/CodebookEditorPanel.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/curation/CodebookCurationPanel.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/CodebookTagEditorPanel.html
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/CodebookTagEditorPanel.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/CodebookTagSelectionPanel.html
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/CodebookTagSelectionPanel.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/ProjectCodebookPanel.html
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/project/ProjectCodebookPanel.java
webanno-codebook/src/main/java/de/tudarmstadt/ukp/clarin/webanno/codebook/ui/suggestion/CodebookSuggestionPanel.java

*  removed codebook dependencies from TagSetSelectionPanel by
introducing CodebookCategory and CodebookTag as well as codebook
internal CodebookTagEditorPanel and CodebookTagSelectionPanel
* Please note that this PR includes a lot of code duplication from core code since we thought of this as the only possible way to remove the dependency in TagSetSelectionPanel
* Not visible in the UI. You have to check the DB to see the changes (i.e. 2 new tables)

#1197 - codebook annotation support

---

webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.html
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.html

- Add context menu element to these pages as well
* Open correction or automation page

#1422 - Cannot open correction or automation page

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Use fast versions of selectAt and selectSingleAt from uimaFIT instead of slow streaming versions
* Use "Merge all" in a document with many sentences and annotations

#1414 - Performance improvements for curation mode

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java

- Add sentences and tokens to the right CAS
* Try resetting a document in correction mode

#1424 - Cannot reset document in correction mode

---

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java

- Improved error message
- Ensure that error message is actually shown and not hidden by subsequent exception happening when trying to load the feature editor models by moving feature editor model loading into actionLoadDocument(...)
- Slightly cleaned up actionLoadDocument(...)

#1301 - Error on curation page when all annotators are removed from a project

---

webanno-telemetry/pom.xml
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/DeploymentMode.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetryTraitsEditor.html
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetrySettingsPage.html
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetrySettingsPage.java
webanno-webapp/pom.xml
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java

- Send telemetry at regular intervals
- Differentiate signals depending on whether instance is actively being used or just running
- Bring up telemetry settings again if collector version has changed
* Try running in different deployment modes and check telemetry.

#1433 - Improve telemetry for server deployments

---

webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2003FormatSupport.java

* Add Conll 2003 support
* Create a project, do some NER annotations, export as Conll 2003 and look whether it is in the zip

#1437 - Add Conll 2003 support

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Use selectAt() and fetch first annotation instead of selectSingleAt
* Go to the annotation page
* Switch to the POS layer and enable forward mode
* Annotate a word, make sure that the following word is not annotated
* choose a tag, press enter
* Exception

#1439 - selectSingleAt throws exception instead of returning null

---

webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java

- Check if there is at least one non-expired session

#1446 - Ping should ignore expired sessions

---

webanno-constraints/pom.xml
webanno-constraints/src/main/resources/META-INF/asciidoc/user-guide/constraints.adoc
webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ComplexTypeTest.java
webanno-constraints/src/test/resources/desc/types/TestTypeSystemDescriptor.xml
webanno-constraints/src/test/resources/rules/region.rules

- Documented how to write rules on boolean and integer features
- Added unit tests for boolean and integer features

#194 - Improve documentation of constraints

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialog.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.java

- Move focus to project list (if available) or else to document list
- Allow pressing enter to close the dialog
* Go to annotation page and try using the keyboard in the open dic dialog

#1353 - Keyboard and Open Document

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.java

Fixed by returning current user in user selection.
* closes https://github.com/webanno/webanno/issues/1468
* see issue discription

#1468 - Curatable documents are not shown

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/agreement.adoc

- Update agreement documentation
- Fix NPE when annotators did not yet annotate a document because we try to upgrade a null CAS
- Improve performance by bulk-loading annotated documents per user
- Improve performance by bulk-upgrading CASes and thus avoiding to construct the project type system again for every CAS (hammering the DB)
* Try calculating agreement on projects with multiple documents where not all users have annotated everything and disabling the "limit to finished" option.

#1467 - Modularize agreement

---

webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingFeatureAttachedSpanAnnotationsRepair.java
webanno-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc

- Added the repair action
- Updated documentation
* Hard to manually test unless you have a suitable old correction project

#1489 - Add repair which clear up deleted but still attached annotations

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java

- Fix importing of CURATION documents
- Fix location where CURATION and CORRECTION documents are exported for projects in correction/automation mode

#1488 - Curated documents are not imported

---

webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
webanno-security/pom.xml
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/session/SessionListener.java
webanno-telemetry/pom.xml
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupport.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
webanno-webapp/pom.xml
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoWebInitializer.java

- Listen to sessions being created and closed and update the registry accordingly
- Count the number of unique users per PING period as active users, not just ones logged in when the PING is sent

#1514 - Sessions are never cleared

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js

- Reduce timeout for redraw
- Redraw only brat view without loading data from the server
* Resize window when on annotation page or on other page with brat visualization

#1519 - Optimize re-rendering of brat view when window is resizes

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtension.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistry.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistryImpl.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/Selection.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.html
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_relation.adoc
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/css/theme/custom.less

- Allow creation of long-ranging relations via a context menu action
* Create a new span layer
* Create a relation layer which attaches to the span layer and which allows cross-sentence relations
* Create an annotation on the span layer on the first page of the document
* Switch to the second page of the document and create another of the span annotations
* Switch back to the first page, right click on the span annotation and select "Link to..."

#1030 - Long-ranging relations

---

webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java

- Re-throw the caught exception after cleaning up the failed merge
* See issue

#1541 - Error message about unmergeable annotation swallowed

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.java

- The layout was fixed
- When opening the dialog, the current project is preselected if possible
- When opening the dialog, the user currently being viewed is preselected if possible
* Open annotation page (which opens dialog)
* Open dialog while already on the page and having a document from not-the-first project open
* Open dialog while viewing document from other user

#1547 - Open document dialog issues

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/ThreadLockingInvocationHandler.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysis.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasPersistenceUtils.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java
webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/CasPersistenceUtils.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java

- Introduce a dynamic proxy around CAS objects to check for concurrent thread accesses
* Use the application
* check for ClassCastExceptions because which mean that the proxy may need to be removed via `getRealCas()` 
* check for exceptions due to cross-thread access to the CAS

#1569 - Safeguard CAS against concurrent accesses

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotatorWorkflowActionBarItemGroup.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CuratorWorkflowActionBarItemGroup.java

- Consolidate checks that document is editable and messages that are displayed if it is not editable

#1573 - Changing annotations in finished document

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js

- Send event for action clicks on relations/arcs
- Fix error message "Unable to locate start/end chunks" when clicking on a relation
* Single-click on a relation and check server log (BratAnnotationEditor using debug level logging)
* Try other things involving arcs/relation annotations to ensure they still work

#1579 - Send event when action-clicking on a relation

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/css/theme/custom.less
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.html

* Move feedbackpanel to the front via high css z-level.
* Check that feedbackpanel still looks the same.

#1583 Move feedbackpanel to front

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTab.java

* Refresh left sidebar tabs after url params are processed for the first time.
* Test that sidebar still looks good and annotation process is still smooth.

#1594 Fix left sidebar when called from url

---

pom.xml
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_server.adoc
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java

- Upgrade to Tomcat 8.5.51
* Build and run application

#1620 - Upgrade to most recent embedded Tomcat 8.x

---

webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasure.java
webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasure.java
webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasure.java
webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java
webanno-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/TwoPairedKappaTest.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiffTest.java
webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeSuiteTest.java
webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java
webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/DescriptionTooltipBehavior.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/bootstrap.scss
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/shim-jquery.scss
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java

- Make code tolerant against layer types not supported by curation
- Simplify CasDiff API
- Small adjustments in JQuery tooltip styles for Bootstrap 4
- Use default Bootstrap 4 fonts
* Improved robustness be tested in vanilla WebAnno
* Test e.g. in INCEpTION https://github.com/inception-project/inception/issues/1628

#1624 - Ignore unsupported layers in curation instead of error

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/MenuBar.html

* Add missing css class
* Add custom navbar items
* Check that they are the same reasonable size 

#1630 - Webanno navbar items do not have fixed height

---

webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/sass/UrlImporter.java

- Do path manipulation without nio paths
* Start webanno in windows and see whether it boots

#1632 - SASS does not compile on Windows

---

webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPage.html

- Adjusted page layout to make charts and table "more scrollable".
* Construct a project with many users and many documents
* View monitoring page

#1638 - Document Status not displayed properly on Monitoring page

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java

*  Set current project when importing or changing settings
* Check whether it still works, no visible changes in webanno

#1643 - Set current project when importing or changing settings

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java

- Check that zip entry is actually a file we care about
* Import projects, especially the one in the issue

#1641 - Project import breaks with zip certain files

---

pom.xml
webanno-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc

- Updated Tomcat 9 version
- Updated servlet API depencency
* Run application

#1651 - Upgrade to Tomcat 9.x and servlet API 4.0

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.html

- Hide checkbox labels along with the checkboxes

#1653 - Labels for import options visible to project creators despite being disabled

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java

- Check whether layer type is annotation or not
* See issue

#1658 - Marking document as finished breaks if CAS contains non-annotations

---

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.html
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java

- Removed the entire functionality to be replaced with a better solution later - right now it is buggy and really slow
* Use the curation page
* Observe that the "invisible annotation" box is gone

#1340 - SuggestionBuilder contains static list of cross-sentence annotations

---

pom.xml

- Upgrade DKPro Parent POM 23 -> 24
- Upgrade uimaFIT 2.4.0 -> 2.5.0
- Upgrade Spring 5.1.9 -> 5.1.15
- Upgrade Spring Security 4.2.13 -> 4.2.15
- Upgrade Tomcat 8.5.51 -> 8.5.54

#1668 - Upgrade dependencies

---

pom.xml

- Upgrade to DKPro Parent POM 24 to allow builds on Java 14
* Build on Java 14

#1472 - Upgrade dependencies

---

webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc

- Backport systemd instructions from INCEpTION
* Apply the instructions to install WebAnno

#1675 - Update documentation for deployment via systemd

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss

- Add z-index for the context-menu class

#1677 - Context menus sometimes do not appear

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/metrics/BratMetricsImpl.java

- Basic check for the window position to avoid checking for differential update when paging
- Added more info to the brat metrics JMX

#1681 - Save time checking for differential update when it will not happen anyway

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.html
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java

- Turn AnnotationFeatureForm into a simple WebMarkupContainer to avoid form submission and AJAX behaviors of buttons and inputs to mess each other up
* Set up a layer with many different types of features including a string feature with a tagset
* Check if everything is working as expected

#1692 - Adding new tags not possible

---

webanno-api-dao/pom.xml
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/metrics/DocumentsMetrics.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/metrics/DocumentsMetricsImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
webanno-security/pom.xml
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/metrics/UserMetrics.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/metrics/UserMetricsImpl.java

* Querying counts of
* documents
* users
* Added MBeans to expose metrics for documents and users
* Add `monitoring.metrics.enabled=true`to your settings.properties file.
* Run Webanno and e.g. check metrics via JConsole

#1684 Get some counts from the database

---

pom.xml

#1668 - Upgrade dependencies (3.6.6)

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/util.js
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js

- Fixed layout if arc labels fall back to layer names
- Changed color of arc labels from the arc color to black to make them better readable, in particular when selected

#1707 - Layout for relations not having a label is broken

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.html

Clear the timer if already set that was set before the ajax call.
The bug has no consequence for Webanno, has to be tested with INCEpTION. See https://github.com/inception-project/inception/issues/1673.
Test with Inception:
1. Change session timeout to something shorter than 30min, e.g. 2min:
* On server: in web.xml change `<session-timeout>2</session-timeout>`
* From .jar: set `server.servlet.session.timeout=2m` in settings.properties
2. Go to AnnotationPage and click through some documents
3. Wait for the timer to run out + 1min + 10s
3. Redirect to login page should happen
Also test, that timer will be reset to 2min if an action was performed.

#1712 Auto logout not succeeding

---

pom.xml
webanno-webapp/pom.xml

- mysql-driver 8.0.15 -> 8.0.20

#1472 - Upgrade dependencies (4.0.0)

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasUpgradeMode.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasAccessMode.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java

Agreement can no longer be calculated (for finished, as well as with unfinished docs).
* see Issue
* uncheck `limit to finished documents`
* check that agreement is re-calculated

#1721 Agreement doesn't work anymore

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java

* Added getcurrentusername which only gets name instead of complete user object
* do some annotation or other, check that it still works

#1738 Add getCurrentUsername to UserDao

---

webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java

Changing the feature after measure selection causes problems.
* added check for no selected feature
* update traits on feature select
1)
* Select feature
* Select measure
* Select *Choose one* for feature
* No nullpointer
2)
* Select feature without traits
* Select measure
* Select feature with traits e.g. *SemPred: Arguments*
* Traits should update
3)
* Check that agreement calculation still works
**Context**
Inception https://github.com/inception-project/inception/issues/1775

#1744 Issues during Agreement selection

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasAccessMode.java

- Fixed conditional
- Made the code clearer to write/read when a CAS should be added to the session by introducing a predicate method

#1751 - UNMANAGED_NON_INITIALIZING_ACCESS gets added to session

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc

- Do not display the delete feature button for features on built-in layers.

#1768 - Features of built-in layers should not be deletable

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/ThreadLockingInvocationHandler.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java
webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java

- Replace the Spring ConcurrentReferenceHashMap with a simpler synchronized WeakHashMap turned into a set because the Spring class seems to "loose" entries without any good reason
- Added a test case for the type-system-changed event
- Added some trace-level logging code for debugging

#1764 - Error when annotating new layer for the first time

---

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.properties

* change checkbox label from "Show disabled users" to "Show disabled user accounts"
n/a

#1773 - Political correctness on user administration page

---

webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetrySettingsPage.html

* fixed some typos
* corrected the side of the button described in the description to match the UI
* check the telemetry settings explanation page 

#1802 - Telemetry Settings explanation improvement

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Replace slow nested loop and repetative calls to contains() with a faster approach
* Try constraints functionality, preferably with very large tag sets and constraint sets

#1804 - Lots of tags and constraints slow interactions down a lot

---

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Replace slow nested loop and repetative calls to contains() with a faster approach
(cherry picked from commit d2136146825fe9410627c489cfdbe9824e68a265)

#1804 - Lots of tags and constraints slow server down a lot (Wicket 8)

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AttachedAnnotation.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AttachedAnnotationListPanel.html
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AttachedAnnotationListPanel.java

- Display incoming/outgoing link/relations in the annotation detail editor panel
* Use an annotation to fill a slot. If you click on the annotation, you should see the slot owner linked in the detail panel
* Create a relation between two span annotations. If you click on either span, you should see the other linked in the detail panel.

#1806 - Display incoming and outgoing relations in the details panel

---

pom.xml
webanno-webapp/pom.xml
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java

- Remove validator bean
- Remove some tomcat deps
* Start webanno in intellij

#1811 - Webanno does not boot in Intellij due to javax errors

---

webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_java.adoc
webanno-webapp/src/main/docker/Dockerfile
webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java

- Upgrade to OpenJDK 11
- Allow the settings.properties file to not be there
* Build docker image
* Run WebAnno from docker image

#1824 - Update Java version in docker file

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java

- Handle ReorderableTag instances in the model
* See https://github.com/inception-project/inception/issues/1897

#1831 - When many tags exist the annotations are not saved

---

webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation.adoc
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database.adoc
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_java.adoc

Recommend to use openjdk in admin guide and fix some typos.
* Build the documentation and read the sections in the admin guide

#1826 Update Java JDK in Admin Guide

---

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java

- Set the user in the state to `CURATION_USER`
- Adjust logging levels a bit
- Update access check to use the actual user and not the user set in the state (which is the `CURATION_USER` now)
* Do a bit of curation and check it still works as expected, e.g. re-merging.

#1836 - Unable to distinguish between curation and annotation events

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorProperties.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorPropertiesImpl.java
webanno-brat/pom.xml
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorProperties.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorPropertiesImpl.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/LoadConfResponse.java
webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/metrics/BratMetricsImpl.java
webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_annotation-editor.adoc
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java

- Moved brat-specific settings to a different properties class
- Updated documentation
- Removed properties from pages where it is no longer directly used
- Made brat properties editable from JMX
* Check that annotation works as expected
* Locate brat properties via JMX and change them - see how it affects e.g. output in the browser console during brat ajax updates
* 

#1845 - Move brat-specific settings to brat module

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnchoringModeType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentStateType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/LinkModeType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ModeType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/MultiValueModeType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/OverlapModeType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevelType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectPermission.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectStateType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ScriptDirectionType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocumentStateType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/StatusType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TrainDocumentStateType.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ValidationModeType.java
webanno-project/pom.xml
webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
webanno-security/pom.xml
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/Authority.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/PersistentEnumUserType.java

- Add caching annotations where sensible
- Made types which are affected by caching serializable as required by 2nd-level caching mechanisms
- Cleaned up a few DAO methods

#1843 - Ready entities for 2nd-level cache support

---

webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/DeploymentMode.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetryDetailsPanel.html

- Added two new deployment modes: JAR_DOCKER and WAR_DOCKER
* Run in docker and check deployment mode in the telemetry configuration page

#1847 - Detect Docker

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.properties
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.properties
webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedTagSet.java
webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/ProjectTagSetsPanel.java

- Removed unused properties
* Export/import a tagset

#196 - "typeUiName" in tagset JSON export unnecessary

---

webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/WicketUtil.java
webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelBase.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/guidelines/ImportGuidelinesPanel.java

- Do not add components to the target which are not visible in the component hierarchy

#1581 - Wicket Ajax error when refreshing settings-page

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java

- Use the username of the current user instead of the username of the user stored in the annotator state when loading preferences

#1867 - Preferences on curation page do not take effect

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java

- Make sure the feature is looked up from the right type system
- Use a default value depending on the feature type if the feature itself could not be found
- Added missing returns in getFeatureValue

#1869 - Error during curation if CASes not fully upgraded

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceAction.java
webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceLoader.java
webanno-ui-project/pom.xml
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java

- Add support for safely performing force bulk actions on CASes such as repairing / analyzing them
- Use this support in the ProjectCasDoctorPanel

#1871 - Repairing CASes does not work

---

webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementUtils.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java

* Fixed the typo mentioned in Issue #1873

#1873 fixed typo

---

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js

- Fix exception
* Annotate in Firefox and also in another type of browser

#1875 - Exception when selecting certain annotations in Firefox

---

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java

- Added unit tests
- Fixed bug that CAS may get deleted
* Try annotating and also provoke a concurrent access

#1878 - Concurrent access protection deletes annotations

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/FeatureFilter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java

- Added unit test
- Fixed issue
- Cleaned up additional unit tests
- Moved comparison of annotations into the adapters

#1885 - Cannot merge two relations with the same target

---

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java

- Fix error by checking for empty/null input before trying to look up a matching user
* See upstream issue description

#1889 - Error when property hideUsers is set

---

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/DanglingRelationsCheck.java
webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java
webanno-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java

- Delegate deletion of attached relations properly to the respective adapter
- Added / expanded checks and repairs to test for this kind of dangling relations

#1893 - Deleting a span to which relations connect leaves dangling relations

---

webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java

- Need to use the types from the target CAS when selecting

#1895 - Merging relations and slots is broken

---

webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocument.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java
webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/model/TelemetrySettings.java

- Fix timestamp setting condition
* E.g. create a new user and then check the creation timestamp in the DB

#1899 - Creation timestamp not set properly on some tables

---

webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasure.java

- Fixed issue by ensuring that annotations extracted from CASes are re-based using the offset of the document containing them within the batch continuum

#1901 - Unitizing agreement not properly calculated

---

pom.xml
webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
webanno-webapp/pom.xml

- DKPro Parent POM 24 -> 26
- Jackson 2.9.10 -> 2.13.0
- UIMA Java SDK 2.10.4 -> 2.11.0
- Spring Security 4.2.15 -> 4.2.20
- SLF4J 1.7.26 -> 1.7.32
- Log4J 2.7 -> 2.15.0
- Wicket 8.11.0 -> 8.13.0
- Wicket Bootstrap 2.0.10 -> 2.0.15
- Wicket JQuery Selectors 2.0.6 -> 2.0.11
- Wicket Webjars 2.0.15 -> 2.0.20
- Wicket Spring Boot 2.1.7 -> 2.1.9
- Hibernate 5.3.10 -> 5.3.24
- Mockito 2.27.0 -> 2.28.2
- AssertJ 3.19.0 -> 3.21.0
- Tomcat 8.5.63 -> 8.5.73
- MySQL Driver 8.0.20 -> 8.0.27
- JUnit 4.13.1 -> 4.13.2
- Commons IO 2.6 -> 2.11.0
- Commons CSV 1.8 -> 1.9.0
- Commons Lang3 3.10 -> 3.12.0
- Hibernate Validator 5.3.5 -> 5.3.6
- Javasisst 3.25.0 -> 3.28.0
- Byte Buddy 1.9.12 -> 1.12.3
- HSQLDB 2.4.1 -> 2.6.1
- cglib-nodep -> 3.3.0
* No specific …

#1932 - Upgrade dependencies

---

pom.xml

#1947 - Dependency updates
