webanno-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController.java
This is for version 1 of API.
While version 2 is work in progress now, I still wanted to contribute this change, as this extra slash requirement returns an error if test this with CURL without explicitly adding the slash at the end.
It is inconsistent that this particular API endpoint needs the extra slash at the end, while all others don't.
=> #411 remove an extra slash from Remote API v1

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Split constructor to several methods
- Remove unnecessary instance variables
- Inline method parameters
- Move getter and setter to the bottom
- Delete unused method parameters
- Change access modifier
=> #486 - Refactoring project structure (3.3.0)

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectLayersPanel.java
When one wants to create a new layer and clicks in the layer-name-field and selects from the
drop-down-list, which shows the previously typed in layer-names, an exception gets thrown or the application complains that this layer already exists although it doesn't.
The problem is that the the layer-name-field only gets triggered on an keyup-  instead on an input-event.
=> Bug when creating a layer with a name from the dropdown

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeUtil.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ProjectInitializer.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/EntityType.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/RelationType.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js, webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/LayerNameAbbreviationTest.java
Includes fixes for:
* #708 - Support morphological features from CoNLL formats
* #709 - Optimize render data size for annotations without labels
* #720 - Automatically abbreviate long layer names in annotations
=> Morphological features and layer name display optimizations

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebar_ImplBase.java
- Old actionShowSelectedDocument method changed to actionShowSelectedDocumentByTokenPosition and deprecated
- Created new actionShowSelectedDocument method based on the offset
instead of token position
=> actionShowSelectedDocument should be offset-based

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
- Add spacers between rows
- Add spacers at beginning and end of rows
- Always render using SVG text elements, even in LTR mode to avoid maintaining two different rendering branches
- Disable pointer events on unrelevant areas during text selection
=> #724 - Cross-row selection is jumpy

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotationPreference.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/AnnotationPreferencesDialogContent.java
- refactor logic from preferred layers to hidden layers, which resolves the hidden new layers startout hidden issue by assuming no layer is hidden in the beginning
- *NOTE* this is a branch from patch-755
=> #752 - New annotation layers start out hidden

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditor.html
- Remove whitespace
- Add wicket enclosure to control visibility of extra NBSP separating constraints indicator in text feature editor
=> #768 - Feature editor labels not aligned

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.html
Reducing the refresh rate reduces the load on my machine from constant 10% to 0% with spikes of 10.
=> Fix #809 Unnecessary CPU load caused by autologout timer

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/action/AnnotationActionHandler.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
Extend forward annotation to free-text annotation feature when
1) it is locked-to-token annotation layer
2) There is only one annotation feature which is enabled and visible at a time. If there multiple features, they should be invisibile and disable to allow forward annotation for free-text annotation
How it works
1) enable forward annotation (using the checkbox)
2) type the annotation in the text-field and pres the ENTER KEY
If nothing is typed in the text-field, annotation will be delted and focus will move to the next token
=> #842 - Extend forward annotation to a feature without a tagset

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java, webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
- Improved layer name validation
- Fixed creation order (layer / features) to avoid org.hibernate.TransientPropertyValueException
- Moved creation of default features into the type adapter
=> #989 - Cannot create chain layer

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/event/AjaxAfterAnnotationUpdateEvent.java
- Only one overall event instead of one per feature since the even receivers might e.g. use the event to switch to another document which would reset the feature states and cause a concurrency problem
=> #1003 - Fire only one AjaxAfterAnnotationUpdateEvent

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
- When rendering iterate over all layers in the project, then get color, then skip if the layer is not visible. This ensures stable colors with regards to layer visibility (not with regards to layers being enabled/disabled, but that is ok).
Fixes #783
=> #783 - Color of a layer changes depending on how many layers are enabled

webanno-brat/pom.xml, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java, webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtilityTest.java, webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
- Changed clearJcasAnnotations to not persist the cleared CAS to disk - calling code was changed to do this
- Changed clearJcasAnnotations to create a DocumentMetaData in the target JCas if it was not there
- Added unit test for clearJcasAnnotations
=> #896 - Handle case where imported XMI file does not contain DocumentMetaData

webanno-diag/pom.xml, webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheck.java, webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIngoingRelationsCheck.java, webanno-diag/src/main/resources/META-INF/asciidoc/developer-guide/casdoctor.adoc, webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheckTest.java
We have a corpus that was annotated with an older version of WebAnno, where the annotators could accidentally add dependency relations with the same target token. This will fail to export with both the CONLL-2009 and the WebAnnoTSV exporter and we now have to correct all the files manually, since there is no way to output these to any format we can read.
Since which edge should be removed (or reversed) only can decided manually, I added a check to the CAS Doctor that finds all offending instances and outputs a message that includes the sentence number (useful to jump directly to the problem) and the actual offending dependency edges.
I'm fairly new to the data model, if there is anything I should improve in the implementation please let me know.
=> Add check for multiple ingoing edges

webanno-diag/pom.xml, webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java, webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheck.java, webanno-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheckTest.java
- Introduce new WARN log level for CAS Doctor checks
- Apply NoMultipleIncomingRelationsCheck only for the DKPro Core Dependency layer
- Demote its log results to WARN and make the check not fail the analysis
=> #1049 - NoMultipleIncomingRelationsCheck reports at ERROR level

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ArcAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/CreateRelationAnnotationRequest.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/CreateSpanAnnotationRequest.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerSupport.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java, webanno-ui-curation/pom.xml, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/MergeCas.java, webanno-ui-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/CopyAnnotationTest.java
- Remove unnecessary fields in ArcAdapter and obtain values from layer instead
- Move behavior code into separate methods in ArcAdapter and SpanAdapter and encapsulate annotation creation parameters into a command class
- Change in behavior: When trying to create a span at a location where a span is already existing and stacking is not enabled, generate an error instead of selecting the existing span
=> #1170 - Reorganize behavior code

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationCrossSentenceBehavior.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanCrossSentenceBehavior.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VRange.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java, webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/controller/BratAjaxCasUtilTest.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Fixed bug causing span annotations on single-token sentences to be considered overlapping sentences
- Fixed bug causing token-locked span annotations being created on single-token to be rendered wrongly (over the entire preceding sentence plus over the single-token sentence)
- Changed forward handling code such that it only becomes active when forwarding is indeed activated and removed redundant stacking check code
- Added debug mode to brat renderer which can be turned on via a constant in the code
- Improved unit tests
=> #1196 - Crossing sentence bounardies is not permitted

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java, webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupportTest.java, webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupportTest.java, webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Tag.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Move handling of tagsets into `PrimitiveUimaFeatureSupport` and `SlotFeatureSupport`
- Extended `SlotFeatureSupportTest` and added `PrimitiveUimaFeatureSupport` to check if tagset handling works
- Remove unused `FeatureSupport.isTagsetSupported` method
* Basically try out features with tagsets (string features as well a slot features with open and closed tagsets) in different contexts (annotation, curation, etc.)
=> #1218 - Handle feature value validation against tagset in FeatureSupport

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/OrthographyLayerInitializer.java, webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfReader.java, webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfWriter.java, webanno-io-tcf/src/test/resources/tcf04-karin-wl.xml, webanno-io-tcf/src/test/resources/tcf04-karin-wl_expected.xml
- Fixed NPEs when importing/exporting orthography annotations where the operation is not yet
- Make the operation feature on the orthography layer required by default since it doesn't really make much sense if it remains unset
* See issue
=> #1233 - NPE when exporting Orthography without operation as TCF

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Properly use the default layer instead of the selected layer when forwarding or creating annotations
- Prevent the Token layer from sneaking into the layer selection - although it never actually shows up, it could be pre-selected so far in certain project configurations
* Disable all layers and try creating an annotation
=> #1252 - Cannot annotate custom layer unless first select existing annotation

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Reverted a change introduced in e17d1fdc1f13f5b74d7ad5e847c2c27403fea759 wrongly assuming that the layer indicating the annotation type to be updated/created would be stored in defaultAnnotationLayer which is not the case when creating relation annotations.
* Create two POS annotations
* Try connecting them using a Dependency relation
=> #1257 - Unable to create relation annotations

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
* Don't set selectedAnnotationLayer of the AnnotatorState when the value of the dropdown field changes
* Set rememberLayer = true in the configurations
* Go to annotation page and select an existing annotation
* Change default layer in the dropdown field
* Check that ```selectedAnnotationLayer``` is not effected
=> #1268 - Changing the annotation layer in the dropdown field internally changes selectedAnnotationLayer

webanno-io-conll/NOTICE.txt, webanno-io-conll/pom.xml, webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUFormatSupport.java, webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUReader.java, webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUWriter.java, webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllCoreNlpReaderWriterTest.java, webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUReaderTest.java, webanno-io-conll/src/test/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUReaderWriterTest.java, webanno-io-conll/src/test/resources/conll/u/conllu-en-orig.conll, webanno-io-conll/src/test/resources/conll/u/conllu-en-orig2.conll, webanno-io-conll/src/test/resources/conll/u/conllu-en-ref.conll, webanno-io-conll/src/test/resources/conll/u_v2/conllu-morphological_annotation.conll, webanno-io-conll/src/test/resources/conll/u_v2/conllu-sentence_bounaries_and_comments.conll, webanno-io-conll/src/test/resources/conll/u_v2/conllu-syntactic_annotation.conll
- Temporarily backport latest DKPro Core CoNLL-U reader and writer code to enable reading/writing of sentence text comment and sentence ID comment
* Check if the export in CoNLL-U format contains the sentence text comment
* A sentence ID comment is only present if the file was originally imported from CoNLL-U and contained a sentence ID
=> #1282 - Missing comments on export to CONLL-U

webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/spring/ApplicationEventPublisherHolder.java, webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/spring/ApplicationEventPublisherHolderImpl.java, webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java, webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/RemoteApiPropertiesImpl.java, webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
Refers to issue https://github.com/inception-project/inception/issues/780.
Wicket @SpringBean injection generates illegal access warning on recent JDKs. This is solved by using existing interfaces or creating new ones. 
* Add --illegal-access=debug to the VM arguments
* Use a recent JDK (9 or higher)
* Access pages which use bean injection
=> #1300 illegal access warning on injection

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasMetadataUtils.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImplTest.java, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasUpgradeMode.java, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java, webanno-api/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/api/type/webanno-internal.xml, webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController2Test.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Added sourceDocumentName and projectName to the CasMetadata
- Added option for readAnnotationCas to upgrade the type system during read
- Upgrade and add CasMetadata in one go when opening a document through the AnnotationPage
* Internal refactoring that is difficult to manually test - in theory you'd try opening a document with CAS with does not have a CasMetadata annotation yet (from an old project) and check in the log if there is *no* message about CasMetadata not being supported and thus not being added
=> #1318 - Allow upgrading of CAS during load

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ClassicKendoComboboxTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/Select2TextFeatureEditor.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Change feature label HTML code such that a span is used instead of a wicket:container as no style/JS can be attached to the latter
* Hover over the label of any feature to bring up a description tooltip
=> #1322 - Display feature description as tooltips

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java, webanno-ui-project/pom.xml, webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- For the start provide a better error message if there are no curatable annotation documents even if a source document can be opened for curation
- Remove unused `setSourceDocumentState()` method
* This PR doesn't fix the issue, but makes it a bit better to deal with it.
=> #1301 - Error on curation page when all annotators are removed from a project

webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java, webanno-io-tsv/src/main/resources/META-INF/asciidoc/user-guide/webannotsv.adoc, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3ReaderWriterRoundTripTest.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTest.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTestBase.java, webanno-io-tsv/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespace/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespaceAtStart/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespace/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespaceAtEnd/reference.tsv
- Truncate parts of an annotation that exists in inter-token space
- Update documentation
- Add unit tests
* See issue description - cannot be reproduced through UI
=> #726 - Whitespace treated incorrectly at the end of spans in TSV3X exporter

webanno-constraints/src/main/resources/META-INF/asciidoc/user-guide/constraints.adoc, webanno-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc, webanno-doc/pom.xml, webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml, webanno-doc/src/test/java/de/tudarmstadt/ukp/clarin/webanno/doc/GenerateDocumentation.java, webanno-webapp/src/main/docker/README, webanno-webapp/src/main/docker/docker-compose.yml
- Embed the Docker Compose script directly into the Admin Guide to allow replacing the version string and not having to use `latest`
- Fix heading level of documentation sections on constraints and CAS doctor
- Added small program to build documentation without having to do a Maven build (backported from INCEpTION)
=> #1361 - docker-compose instructions do not work

webanno-api-annotation/pom.xml, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Added a hidden field at the after the last feature editor which directs the focus back to the last feature editor
- This extra field also fixes the bug... but for good measure, we also prevent plain text feature editors from submitting the form
- Use bootstrap "checkbox" instead of a regular one
- Try to smartly restore the focus if it gets lost when some feature is edited
* In general, edit some annotations, in particular some with multiple features and using tab or enter to commit feature values
=> #1338 - Relation feature is not saved when pressing enter

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
- enable annotation links for other annotation types than spans in the UI when editing features
- change LinkFeatureEditor to not be dependend on a surrounding form
* Try using slot features in all imaginable ways with and without tagsets
=> #1378 - Enable document annotation link features

webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3ReaderWriterRoundTripTest.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTest.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTestBase.java, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBeforeFirstTokenIsMovedToBeginOfFirstToken/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBeforeFirstTokenIsMovedToBeginOfFirstToken/reference.xmi, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBetweenTokenIsMovedToEndOfPreviousToken/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBetweenTokenIsMovedToEndOfPreviousToken/reference.xmi, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBeyondLastTokenIsMovedToEndOfLastToken/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testZeroWidthAnnotationBeyondLastTokenIsMovedToEndOfLastToken/reference.xmi
- Added unit tests for zero-width annotations in inter-token space
- Move these around during export to cling to an appropriate token instead of crashing
* Run the unit tests (no manual testing since effect cannot be triggered through the UI)
=> #1384 - Zero-width annotations in pre-/post-/inter-token space crash TSV export

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java, webanno-curation/pom.xml, webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java, webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
- Avoid using Map.containsValue(...) in isAgreement(...) and isComplete(...) - it is currently only being used for a redundant sanity check of the parameter and it is very slow.
- Avoid generating an event for every single merged annotation. Instead generate a bulk-update event.
- Cache type adapters in CasMerge since creating a new one involves looking up the feature list in the DB which becomes rather slow when the type adapter is repeatedly looked up.
- Avoid using CasUtil. selectCovering and instead use streaming operations on the annotation index for a bit of speedup in operations like selectAt.
* Try using curation mode with a large documents with many annotators and many annotations
=> #1414 - Performance improvements for curation mode

webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java, webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/event/TelemetrySettingsSavedEvent.java, webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
- Send the telemetry settings along with the TelemetrySettingsChanged event and check the latest settings before triggering the transmission
=> #1413 - Telemetry sent one last time when it is disabled

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
- fix visibility setting for delete button in LinkFeatureEditor
1. Open a document that has a layer with a link feature
2. Select an annotation that has a link
3. Select the filled slot
4. Delete button is there
5. Click it to test functionality
=> #1411 - Delete button for LinkFeatureEditor missing

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ClassicKendoComboboxTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureEditor.java
- add form-control css class to feature editor inputs
- remove duplicate call of add() method in NumberFeatureEditor
* ...
=> #1417 - Feature editors missing form-control CSS class

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/CurationPanel.html, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/CurationPanel.java
- Remove enclosure and add container instead
- Add a comment to the HTML to avoid another regression
* Open document with many sentences
* Scroll down
* Select a sentence
* Observe that sentence list does **not** jump back to top
=> #1427 - Sentences list jumps back to top again

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/exception/IllegalFeatureValueException.java, webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
- For the moment ensure that the curation doesn't crash and that the page can be opened
- There is no user information at the moment indicating that an annotation was skipped and why because the information is generated quite deeply in the backend code and we first need to add some way to bubble this information up to the UI
- If there is a problem copying a feature value, then the entire annotation is not merged (instead of creating the annotation but not merging the feature values)
- The sentence overview or annotator view does not show any indication that there is an invalid annotation (no validation)
=> #1430 - Out of tagset tag crashes curation

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
- when setting annotation layers check if the new selected annotation layer and default selected annotation layer is of type span
1. Create a fresh project
2. Disable all layers
3. Create a span layer, named for example `ASPAN`
4. Create a document layer, named fpr example `ADOC` (if sorted `ADOC` occurs before `ASPAN` in alphabet)
5. Add a document to the project
6. Open the editor and try to create a span
=> #1465 - Selected default layer is not a span layer

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextAreaFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextAreaFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraits.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraitsEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/UimaStringTraitsEditor.java, webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_primitive-features.adoc, webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
- Add option for multiple rows and count of collapsed and expanded rows for primitive string features
- Use normal input textfield feature if multiple rows is disabled, otherwise use input textarea
* Create a new string feature for a layer and enable multiple rows
* Set collapsed and expanded rows
* See results in the annotation editor
=> #1455 - Larger string input features for annotations

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RatingFeatureEditor.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- clear slot and send RenderSlotsEvent when creating or updating a span annotation and send RenderSlotsEvent
- generated new random serialVersionUID for rating feature
1. Open a span annotation
2. Arm a slot in a link feature
3. Modify another feature like a string or number feature.
4. Slot should be disarmed and the other feature should be updated
=> #1483 - Crash when modifying annotations while slot is armed

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/BooleanFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/FeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RatingFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RatingFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Allow the addAnnotateActionBehavior() to handle choice form components (i.e. RadioGroup)
- Simplify RatingFeatureEditor code and HTML
- Changed return type of getFocusComponent to FormComponent since the addAnnotateActionBehavior only works for FormComponents
- Handle all Wicket default choice component types
- Do not set the markup ID of the feature container as the throttling/timeout ID to avoid timers for different features cancelling each other out
1. Have a string feature
2. Have a rating feature
3. Edit the string feature text
4. Click on a value of the rating feature
5. String feature changes should be saved
=> #1496 - Focusing Rating Editor breaks updating of other features

webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java, webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/model/TsvSchema.java, webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/model/TsvUnit.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTest.java, webanno-io-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTestBase.java, webanno-io-tsv/src/test/resources/tsv3-suite/testElevatedType/reference.tsv, webanno-io-tsv/src/test/resources/tsv3-suite/testElevatedType/reference.xmi
- Export elevated types as whichever of their supertypes is actually part of the TsvSchema (i.e. a subtype of Annotation)
- Added unit test
=> #1539 - WebAnnoTsv3XWriter does not support elevated types

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java, webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv1FormatSupport.java, webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv2FormatSupport.java, webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3FormatSupport.java, webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java
- Fix issue that curation is always exported as TSV in AUTO mode
- Give WebAnno TSV formats better names
- Improve info messages when falling back to TSV3
- Sort list of formats on the project export page properly
* Export a project with non-TSV original file format as AUTO
=> #1551 - "AUTO" format always exports curated documents as TSV3

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/PagingStrategy.java
- Paging should be based on the first visible unit, not based on the focus unit.
* Open a document
* Annotate something in row 4
* Switch to the next page
* Page should start with 5 now, not with 9 as before
=> #1553 - Navigation in annotation view skips sentences

webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Avoid saving the upgraded CAS when viewing another user's data
- Avoid verifying the timestamp when viewing another user's data - no need to because we don't save anyway
- Add additional safeguard into writeEditorCas() to throw an exception if this method is invoked while viewing another user's data
- Avoid logging the rather common AnnotationException with full stack trace and unless in debug mode and just display the user message instead
=> #1558 - Opening the annotations of another user updates CAS

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/DefaultTagSetsInitializer.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/DependencyLayerInitializer.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/PartOfSpeechLayerInitializer.java, webanno-api-dao/src/main/resources/tagsets/mul-dep-ud2.json, webanno-api-dao/src/main/resources/tagsets/mul-pos-ud2.json, webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagEditorPanel.html, webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.html
- Upgrade default POS and dependency tagsets to UDv2
- Do not install unused tagsets
- Prevent resizing tagset and tag description text areas horizontally
* Create a project and check the layers are there and the tagsets are there
=> #1521 - Upgrade to UDv2 POS and dependency tagsets

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/FeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RatingFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/event/FeatureEditorEvent.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/event/FeatureEditorValueChangedEvent.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/event/LinkFeatureDeletedEvent.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/event/LinkFeatureEvent.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
- Extended FeatureEditorEvent to allow access to the sending editor
- Move updating code into the feature editors
- Send events when an update has happened
- Move event handlers from ADEP into AnnotationFeatureForm
* Annotate some text with different types of features, also multiple features of different types in a single layer
=> #1561 - FeatureEditors should handle their updates themselves

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java, webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- Take attach-feature into account when offering layers to attach to on relation creation
- Hide attach feature field when not using a relation
- Add a display-only widget which shows the attach layer + attach feature + attach feature target layer for comprehensive information
- Don't allow attaching to the Token or Sentence layers
- Use a more modern lambda-aware code style for building the UI elements in Java
* View **Dependency** layer in project settings and see the full attach-layer + attach-feature info
* Go through the different layers and see the attach-feature info appearing and disappearing
* Create a custom relation layer attaching to some other layer - make sure you cannot attach to a layer which has already another relation …
=> #1571 - Forbid creating relation layers on layers that already have a defined relation

webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2000.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2002.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2003.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2006.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2009.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conll2012.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conllcorenlp.adoc, webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-conllu.adoc, webanno-io-tsv/src/main/resources/META-INF/asciidoc/user-guide/webannotsv.adoc
- Disable auto-conversion of tabs to spaces
- Fix examples
* Copy-paste some of the CoNLL examples to files and then try to import them.
=> #1587 - Several format examples cannot be used copy-paste

webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.html, webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UsersProjectSettingsPanelFactory.java
Changed component order of *Users* tab on *Settings Page*. Also gave the tabcontainer on the page a name, so I can reference it in js.
* Look at Settings page and make sure that all tabs are still there and the Documents tab comes before the Users tab.
=> #1589 Changing order of Tabs in Settings

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/GuildelinesExporter.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/ProjectLogExporter.java
- Fix ZIP entry names where code looks for project log and guidelines
=> #1635 - Guidelines and project log not properly reimported

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
See https://github.com/inception-project/inception/issues/1647
* If no query params are given for request, do not go with default of opening at first page.
* Open a document to a later page
* Open the sidebar
* The document should not jump to the first page
* Please also test different variations of opening documents in different projects etc. to make sure, page navigations works otherwise.
=> #1648 Opening the sidebar jumps document back to first page

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- Skip disabled link features during rendering
* Create an annotation of type **SemPred** and link to a **SemArg**
* Enter project settings and disable **arguments** feature on the **SemPred** layer
* View again on the annotation page and see that there is no link rendered anymore
=> #1629 - Hide/Invisible Link Feature in annotation view

pom.xml
- Mockito 2.28.2 -> 3.3.3
- AssertJ 3.14.0 -> 3.15.0
- Spring 5.2.4 -> 5.2.6
- Spring Boot -> 2.2.4 -> 2.2.6
- Spring Security 5.2.2 -> 5.2.3
- Wicket 8.6.1 -> 8.8.0
- Wicketstuff 8.6.0 -> 8.8.0
- Wicket Bootstrap 3.0.0-M13 -> 3.0.0-M15
- Wicket JQuery Selectors 2.0.8 -> 2.0.9
- Wicket Webjars 2.0.17 -> 2.0.18
- Log4J 2.12.1 -> 2.13.2
- JBoss Logging 3.3.1 -> 3.4.1
- Hibernate 5.4.10 -> 5.4.15
- Hibernate Validator 6.1.0 -> 6.1.4
- Batik 1.11 -> 1.12
- Jackson 2.10.2 -> 2.11.0
- Tomcat 9.0.33 -> 9.0.34
=> #1472 - Upgrade dependencies

webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.html, webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java, webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.html, webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.properties, webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/OverviewListChoice.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.properties, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.properties, webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java, webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.properties
Add some explanations to empty (or confusing) spaces.
* AgreementPage: 
* added explanation on what to do when table is empty (only zeros and no positions) to the legend
* do not show table if there are no raters/documents, show an error message instead
* AnnotationPage and CurationPage: added message and popover explanation if document list is empty in LoadDocumentDialog
* Check agreement table for no documents and if it works as expected otherwise
* Try out load document dialog on annotation and curation page
=> #1727 Add messages to empty spaces

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorRenderedMetaDataKey.java, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
- Always use deferred rendering when the editor is part of a full or partial page update
- Detect if a partial page update is in scheduled for the editor and if that is the case, avoid adding a render JSON command to the current AJAX target
=> #1714 - Document does not show after sidebar close

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.properties, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/guidelines/GuidelinesActionBarItem.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/PreferencesActionBarItem.html, webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java, webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/LayerNameAbbreviationTest.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/AnnotatorWorkflowActionBarItemGroup.html
Added "..." when a name of a layer is abbreviated. If abbreviation + "..." 
* Open any document on the annotation page
* Annotate a short span of ~3 character (layers SemPred/SemArg are very good for this) and see the abbreviated layer names in the bubble above the span ending with "..."
* Annotate a short span with short layer name and see the layer name will not be abbreviated (since the whole name is not longer the abbreviation +" ...").
* Annotate a long span and see the layer name will not be abbreviated.
=> #1734 add abbreviation marks

webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Add option to force-recreate the merge CAS when loading it
- Remove upgrade for all finished annotation documents when loading the merge CAS - IMHO that should not be necessary anymore
- Instead of deleting the curation CAS on disk and then re-create it implicitly (which currently does not work because we simply get the copy from memory when we try this), just create a new merge CAS and then overwrite the curation CAS with the new merged version.
* See (upstream) issue description
=> #1757 - Re-Merge does not work anymore

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageSession.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/PooledCasHolderFactory.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/SessionManagedCas.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java, webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentService.java, webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
* invalidate casholder object in exclusiveaccesspool when deleting a cas
* call method that removes cas from pools when re-merging
* Test that re-merging during curation will reset the curation document again
* Check annotation process for buggy behaviour
=> #1749 Really destroy cas when deleting cas

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java
- Fixed exception being thrown as part of the logging when handling an exception while trying to load a CAS causing the borrowed CAS holder for this CAS never to be returned which in turn caused a deadlock *puh*
- Added maximum wait time for borrowing a CAS
=> #1771 - Curation page does not load

webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/WebAnnoDaoAuthenticationProvider.java, webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java, webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java, webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java, webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoSecurity.java
- Extra guard against users with emtpy passwords (i.e. those created by pre-auth) trying to access the remote API
- Allow the remote API to authenticate against the internal user DB even if external authentication is enabled
- Include username in message when saving user details
* Enable the remote API in the `settings.properties` file: `remote-api.enabled=true`
* Create a user `jack` with `ROLE_REMOTE`, `ROLE_USER`, and `ROLE_PROJECT_CREATOR`
* Log in as `jack` and create a project
* Enable external authentication in `settings.properties`:
```
auth.mode                     = preauth
auth.preauth.header.principal = remote_user
```
* Restart
* Try accessing the remote API as `jack` at `curl -k -X GET …
=> #1776 - Unable to use remote API when external authentication is enabled (3.6.x)

webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/WebAnnoDaoAuthenticationProvider.java, webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java, webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java, webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java, webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoSecurity.java
- Extra guard against users with emtpy passwords (i.e. those created by pre-auth) trying to access the remote API
- Allow the remote API to authenticate against the internal user DB even if external authentication is enabled
- Include username in message when saving user details
* Enable the remote API in the `settings.properties` file: `remote-api.enabled=true`
* Create a user `jack` with `ROLE_REMOTE`, `ROLE_USER`, and `ROLE_PROJECT_CREATOR`
* Log in as `jack` and create a project
* Enable external authentication in `settings.properties`:
```
auth.mode                     = preauth
auth.preauth.header.principal = remote_user
```
* Restart
* Try accessing the remote API as `jack` at `curl -k -X GET …
=> #1776 - Unable to use remote API when external authentication is enabled (master)

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Nullpointer exception was thrown during annotation when feature was added by another users.
- null checks
- error message on EditorDetailPanel load if feature non-existent
- User 1: annotate with layer A
- User 2: add a feature to layer A in Settings
- User 1: try annotating
- Please also test that "nomal" annotation still works
=> #1770 Adding features to layer should prompt other users to re-open

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
* Set layer as default when only one
* Create project, add document, disable all layers except for one
* Open annotation page
* Try to create a span annotation
* Enable more layers and test that we can still normally select annotations and select layers
=> #1783 'No layer is selected' when only one layer enabled

webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
Sometimes features of previously selected annotations were still shown.
*  Feature editor is not visible when no selected layer
* Select annotation
* Open AL session or re-merge from curations sidebar
* Right sidebar should show no layer selected and also no features
=> #1785 Feature Editor wrongly shown

webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/io/FastIOUtils.java
- Add explicit type cast to avoid linking to a non-Java-8 version of the flip() method
- Fixes #1795
=> #1795 - WebAnno versions compiled on recent JDKs do not run on JDK 8

webanno-constraints/pom.xml, webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ConstraintsParserTest.java, webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/UnicodeRulesTest.java, webanno-constraints/src/test/resources/rules/unicode-characters.rules
- Build constraint grammar parser with Unicode support
- Added unit tests for rules containing Unicode characters
* You can also import the file `webanno-constraints/src/test/resources/rules/unicode-characters.rules` included with this PR - lots of Unicode chars
=> #1791 - Cannot parse constraint rules with non-ASCII characters anymore

webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-uimaxmi.adoc, webanno-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/XmiXml11FormatSupport.java
- Added support for CAS XMI XML 1.1
* Try exporting a document containing characters that are supported in XML 1.1 but not in XML 1.0 (e.g. 0x0001).
=> #1797 - Support for UIMA CAS XMI XML 1.1

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/action/AnnotationActionHandler.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.html, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/Selection.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.properties, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationInfoPanel.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationInfoPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationTextPanel.html, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationTextPanel.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AttachedAnnotationListPanel.java, webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_link-features.adoc, webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_relation.adoc, webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/AnnotationSelection.java, webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects.adoc
- Added jump-to-target buttons for relations and also for link features
- Use a hand pointer over link features to indicate that clicking on them triggers an action
- Improved API for jumping to places
- Include the layer of the target in the role label or relation target label
* Create a relation between two spans
* Click on the relation and observer that instead of the "text" field there are now "from" and "to" fields with navigation buttons (crosshair)
=> #1809 - Navigate to relation endpoints

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/JsonImportUtil.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/TagSetExporter.java, webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java, webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- Batch importing tags into one transaction
- Improve synchronization on event log to avoid empirically observed deadlock with huge tagsets on HSQLDB
- Fix warnings about missing markup IDs on the tagset management panel
* Create a project using the embedded DB
* Import a project with a very large tagset
=> #1291 - Creating tag sets with embedded db slow

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java, webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentStateTransition.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/AnnotatorWorkflowActionBarItemGroup.java
For https://github.com/inception-project/inception/pull/1872 regarding document state for curation when curating from sidebar.
* Fixed that annotation was disabled by adding curation check to `editable`-methods
* Now tracking and transitioning curation document status in annotation mode to support curation sidebar and keep document state up to date (cf. Monitoring Page)
* Annotate, curate and finish documents and check that document state is up to date.
=> #1822 Annotation disabled for curator

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DocumentNavigator.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorDocumentNavigation.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- Show messages that there are not next/prev documents without having to use an exception to do so.
* Try switching beyond the first/last document
=> #1838 - Moving between documents shouldn't throw exceptions

webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
* Get previous url before sign in
* login via `/login` -> be directed to welcome.html page
* log out
* request e.g. a specific document `/annotation.html?3#!p=3&d=9` -> should be re-directed to this document
=> #1860 Redirect to previous url after login does not work

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ClassicKendoComboboxTextFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.java, webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Listen to the SelectionChanged event in the AnnotationDetailEditorPanel and re-render if the selection changes
- Remove outdated logging messages
- Harmonize code to re-read Kendo datasources during rendering
* See https://github.com/inception-project/inception/issues/1791
=> #1865 - Annotation details still shown even tough selection has been cleared

webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageSession.java, webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/SessionManagedCas.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java, webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java, webanno-api-dao/src/test/resources/log4j2.xml, webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
* Ensure exclusive access even for read-only and unmanaged accesses for the moment that the access and potentially an entailing initialization of the CAS from the initial CAS is perfomed.
* No specific manual test procedure. Automatic test included.
=> #1887 - Race condition for shared-read-only access can cause re-initialization of CAS

webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringServiceImpl.java
- The pastelle / non-pastelle settings actually make a difference now
=> #1897 - "Dynamic" and "dynamic pastelle" do not differ

pom.xml
- Downgrade to MySQL driver 8.0.20 again due to classcast exception in liquibase
* Run with MySQL
=> #1937 - Unable to boot WebAnno 3.6.8 with MySQL DB
